### ISSUE TITLE
Can't scroll minutes on iPhone5 in landscape mode

### ISSUE THREAD

**Issue by avgx** [CooperRS/RMDateSelectionViewController#42] opened 2015-01-30 13:50 UTC
To reproduce: 
start demo project
rotate in landscape mode
press "Show date..."

If I rotate after showing the control - all works as expected.

**Comment by CooperRS** [comment] 2015-01-30 14:33
Works for me in simulator and on a real device. Which system language/locale are you using? (As I only tested with german and us locale)

**Comment by avgx** [comment] 2015-01-30 14:38
in simulator. 
en
If found that the issue is due to
```
        if([[[UIDevice currentDevice] systemVersion] floatValue] >= 8.0 && UIInterfaceOrientationIsLandscape([UIApplication sharedApplication].statusBarOrientation)) {
            aDateSelectionViewController.window.frame = CGRectMake(0, 0, [[UIScreen mainScreen] bounds].size.height, [[UIScreen mainScreen] bounds].size.width);
        }
```
in 
```
+ (void)showDateSelectionViewController:(RMDateSelectionViewController *)aDateSelectionViewController animated:(BOOL)animated
```
And I'm prepareing PR, but i haven't solved all cases where i need to put
```
[aDateSelectionViewController.datePicker layoutIfNeeded];
```

**Comment by CooperRS** [comment] 2015-01-30 14:39
OK, then I'm waiting for your PR :)

**Comment by avgx** [comment] 2015-02-03 09:36
Can't get the things working :(
Reproduced with real device iphone5s
1. Start demo
2. rotate UIInterfaceOrientationLandscapeRight
3. press "show date..."
4. the minutes are unavailable to scroll
5. if then rotate to portrait - can't press select button
It seems like touch area is only on original place (where no transform)
If I press "show date..." in portrait orientation - all is perfect for all rotations.

**Comment by CooperRS** [comment] 2015-02-06 10:54
Hmm, I could not find a solution for myself as I could not find the reason why the touch area is broken. But I'll keep working...

**Comment by avgx** [comment] 2015-02-06 12:40
I've found the working code in https://github.com/Busta117/SBPickerSelector but I can't integrate it here, not enouph experience in ios yet.

**Comment by CooperRS** [comment] 2015-04-05 08:43
Acutally this bug should be fixed by using custom transitions instead of UIWindows. I would appreciate if you could take a look at the branch `AppExtensions` and try to reproduce this bug with this branch :)

**Comment by CooperRS** [comment] 2015-04-05 11:29
You may now also try the pod version 1.5.0 ;)

**Comment by CooperRS** [comment] 2015-05-01 08:00
Closing due to missing response.

**Closed by CooperRS** 2015-05-01 08:00 UTC
Labels: bug
